### ISSUE TITLE
Get era_python.qmd to work with DuckDB on Ubuntu

### ISSUE THREAD

**Issue by iangow** [iangow/notes#2]
Starting with setup in #1, I did this:

```
pip install 'ibis-framework[duckdb]'
```

**Comment by iangow** [comment]
@blucap I can get DuckDB to work on Linux (Ubuntu Mate 22.04 LTS). See above (code and PDF in a separate branch).

**Comment by iangow** [comment]
Link to PDF is [here](https://github.com/iangow/notes/blob/9701b3fbe20f2edb1605fd1fd9089ba61ef8b14f/era_python.pdf). Note I had to make a tweak to the SQL to handle (unfortunate) dialect differences. Whoever implemented regexes in DuckDB didn't bother to read the PostgreSQL documentation.

**Comment by iangow** [comment]
Runtime is fine, even on an old (2013) computer:

```
(base) igow@igow-ubuntu-mate:~/git/notes$ time quarto render era_python.qmd --to pdf --quiet  

real	0m20.503s
user	0m22.546s
sys	0m2.020s
```

**Comment by blucap** [comment]
> @blucap I can get DuckDB to work on Linux (Ubuntu Mate 22.04 LTS). See above (code and PDF in a separate branch).



> @blucap I can get DuckDB to work on Linux (Ubuntu Mate 22.04 LTS). See above (code and PDF in a separate branch).

    pip install 'ibis-framework[duckdb]'

Works in my case, yes.

**Comment by blucap** [comment]
> @blucap I can get DuckDB to work on Linux (Ubuntu Mate 22.04 LTS). See above (code and PDF in a separate branch).

    pip install 'ibis-framework[duckdb]'

Works in my case

**Comment by iangow** [comment]
So all good now?

**Comment by blucap** [comment]
Not yet. This issue is this in trying to run `wrds2pg` using the examples given:

    os.environ['PGHOST']="localhost"
    os.environ['PGDATABASE']="crsp"
    os.environ['WRDS_ID']="my_wrds_id"
    os.environ['PGUSER']="postgres"

    wrds_update_pq("funda", "comp", obs=10000, force=True,  data_dir="/home/martien/gow/data/")

This returns an error:

    Traceback (most recent call last):
    File "/home/martien/.local/share/JetBrains/Toolbox/apps/DataSpell/ch-0/232.10227.10/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
    File "<input>", line 6, in <module>
    File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/wrds2pg/wrds2pg.py", line 939, in wrds_update_pq
    modified = get_modified_str(table_name=table_name, 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/wrds2pg/wrds2pg.py", line 443, in get_modified_str
    contents = p.readlines()
               ^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'readlines'

**Comment by blucap** [comment]
When I run this:

    from wrds2pg import wrds_update
    wrds_update(table_name="mcti", schema="crsp")

I get:

    Error: Missing connection variables. Please specify engine or (host, dbname).

**Comment by blucap** [comment]
My system runs Mint 21.2 equivalent to Ubuntu Jammy. 

I run the code using Python 3.11 under DataSpell in a virtual environment with these packages installed:

    Package                  Version
    ------------------------ ------------
    aiohttp                  3.9.1
    aiosignal                1.3.1
    appdirs                  1.4.4
    atpublic                 4.0
    attrs                    23.1.0
    bcrypt                   4.1.2
    bidict                   0.22.1
    cachetools               5.3.2
    certifi                  2023.11.17
    cffi                     1.16.0
    charset-normalizer       3.3.2
    cryptography             41.0.7
    decorator                5.1.1
    duckdb                   0.9.2
    duckdb_engine            0.10.0
    filelock                 3.13.1
    frozenlist               1.4.1
    fsspec                   2023.6.0
    gcsfs                    2023.6.0
    google-api-core          2.15.0
    google-auth              2.25.2
    google-auth-oauthlib     1.2.0
    google-cloud-core        2.4.1
    google-cloud-storage     2.14.0
    google-crc32c            1.5.0
    google-resumable-media   2.7.0
    googleapis-common-protos 1.62.0
    greenlet                 3.0.3
    humanize                 4.9.0
    ibis-framework           7.2.0
    idna                     3.6
    importlib-metadata       7.0.1
    importlib-resources      6.1.1
    Jinja2                   3.1.2
    joblib                   1.3.2
    markdown-it-py           3.0.0
    MarkupSafe               2.1.3
    mdurl                    0.1.2
    multidict                6.0.4
    multipledispatch         1.0.0
    numpy                    1.26.2
    oauthlib                 3.2.2
    pandas                   2.1.4
    paramiko                 3.4.0
    parsy                    2.1
    pins                     0.8.3
    pip                      23.3.2
    protobuf                 4.25.1
    psycopg2-binary          2.9.9
    pyarrow                  14.0.2
    pyarrow-hotfix           0.6
    pyasn1                   0.5.1
    pyasn1-modules           0.3.0
    pycparser                2.21
    Pygments                 2.17.2
    PyNaCl                   1.5.0
    python-dateutil          2.8.2
    pytz                     2023.3.post1
    PyYAML                   6.0.1
    requests                 2.31.0
    requests-oauthlib        1.3.1
    rich                     13.7.0
    rsa                      4.9
    setuptools               69.0.3
    six                      1.16.0
    SQLAlchemy               2.0.23
    sqlalchemy-views         0.3.2
    sqlglot                  20.4.0
    toolz                    0.12.0
    typing_extensions        4.9.0
    tzdata                   2023.3
    urllib3                  2.1.0
    wheel                    0.42.0
    wrds2pg                  1.0.29
    xxhash                   3.4.1
    yarl                     1.9.4
    zipp                     3.17.0

**Comment by iangow** [comment]
Maybe I should open an issue in `wrds2pg`. From the script [here](https://iangow.github.io/far_book/parquet-wrds.html#sec-make-pq), you would need to specify `fix_missing = True` for that table. That said, I don't think that the error message you are seeing comes from that issue (i.e., that SAS emits characters as missing values in some cases).

```python
wrds_update_pq("funda", "comp", fix_missing = True, obs=10000, force=True,  data_dir="/home/martien/gow/data/")
```

Regarding the second one:

     Error: Missing connection variables. Please specify engine or (host, dbname).

You may want to try:

```python
wrds_update(table_name="mcti", schema="crsp", host="localhost", dbname="your_db")
```

Do you have a PostgreSQL instance running? If not, it might be easier to get `wrds_update_pq()` going first.

**Comment by iangow** [comment]
Looking at the packages that I require for `wrds2pg`, this is what I have:

```{python}
req = ['pandas', 'sqlalchemy', 'paramiko', 'psycopg2-binary', 'pyarrow', 'duckdb']
from importlib import metadata
for dist in metadata.distributions():
    if dist.name in req:
        print(f"{dist.name}=={dist.version}")
```

```
psycopg2-binary==2.9.5
pyarrow==13.0.0
paramiko==2.12.0
duckdb==0.9.1.dev97
pandas==2.1.1
```

In most cases, you have a more recent version. Let me see if I get anything different if I upgrade these.

**Comment by iangow** [comment]
Hmm. This works fine (I used `alt_table_name="funda_fun")` so as not to overwrite my current file).

```python
iangow@Ians-MacBook-Pro ~ % python3
Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from wrds2pg import wrds_update_pq
>>> wrds_update_pq("funda", "comp", fix_missing = True, obs=10000, alt_table_name="funda_fun")
Updated comp.funda_fun is available.
Getting from WRDS.

Beginning file download at 21:55:21.
Saving data to temporary CSV.
Converting temporary CSV to parquet.
Parquet file: /Users/iangow/Library/CloudStorage/Dropbox/pq_data/comp/funda_fun.parquet
Completed creation of parquet file at 21:55:45.
True
>>> req = ['pandas', 'sqlalchemy', 'paramiko', 'psycopg2-binary', 'pyarrow', 'duckdb']
>>> from importlib import metadata
>>> for dist in metadata.distributions():
...     if dist.name in req:
...         print(f"{dist.name}=={dist.version}")
... 
pandas==2.1.4
duckdb==0.9.2
psycopg2-binary==2.9.9
pyarrow==14.0.2
paramiko==3.4.0
```

**Comment by iangow** [comment]
From the same terminal window as the one I ran Python from, I have no trouble connecting to WRDS (if this doesn't work, it can be cause the problem you're seeing):

```
iangow@Ians-MacBook-Pro ~ % ssh iangow@wrds-cloud-sshkey.wharton.upenn.edu
Last login: Sat Dec 23 15:23:08 2023 from 71.174.239.121
------------------------------------[ Menu ]------------------------------------

  nedit <filename>                    - Edit/create <filename> using nedit
  pico <filename>                     - Edit/create <filename> using pico
  emacs <filename>                    - Edit/create <filename> using emacs

  qsub <filename>                     - Submit a wrapper script for processing
  qsas <filename>                     - Submit a SAS job directly for processing
  qrsh                                - Start an interactive session
...
```

**Comment by blucap** [comment]
> wrds_update_pq()

Okay, the command:

    wrds_update(table_name="mcti", schema="crsp", host="localhost", dbname="wrds")

Returns:

    crsp.mcti already up to date
    False

That looks promising. 

The command: 

    wrds_update_pq("funda", "comp", fix_missing = True, obs=10000, force=True,  data_dir="/home/martien/gow/data/")

keeps giving the error shown above, `AttributeError: 'NoneType' object has no attribute 'readlines'`

**Comment by iangow** [comment]
Yes, that is promising (it means you are getting "last modified" from the WRDS file).

Run `wrds_update(table_name="mcti", schema="crsp", host="localhost", dbname="wrds")` with `force=True`.

**Comment by blucap** [comment]
This works now, using these steps: 

    import os
    os.environ['PGHOST']="localhost"
    os.environ['PGDATABASE']="crsp"
    os.environ['WRDS_ID']="blucap"
    os.environ['PGUSER']="postgres"
    from wrds2pg import wrds_update_pq, wrds_update_csv, wrds_update
    wrds_update_pq("funda", "comp", fix_missing = True, obs=10000, force=True,  data_dir="/home/martien/gow/data/")

Output:

    Forcing update based on user request.
    Beginning file download at 22:14:37.
    Saving data to temporary CSV.

**Comment by blucap** [comment]
However, now the previous command, that did work for a moment, falters:

    wrds_update(table_name="mcti", schema="crsp", host="localhost", dbname="wrds")

    sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied

**Comment by blucap** [comment]
See larger error warning here: 

    wrds_update(table_name="funda", schema="comp", host="localhost", dbname="wrds")
    Traceback (most recent call last):
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
        self._dbapi_connection = engine.raw_connection()
                                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
        return self.pool.connect()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
        return _ConnectionFairy._checkout(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
        rec = pool._do_get()
              ^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
        with util.safe_reraise():
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
        return self._create_connection()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
        return _ConnectionRecord(self)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
        self.__connect()
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
        with util.safe_reraise():
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
        return dialect.connect(*cargs, **cparams)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 616, in connect
        return self.loaded_dbapi.connect(*cargs, **cparams)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
      File "/home/martien/.local/share/JetBrains/Toolbox/apps/DataSpell/ch-0/232.10227.10/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
        coro = func()
               ^^^^^^
      File "<input>", line 1, in <module>
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/wrds2pg/wrds2pg.py", line 699, in wrds_update
        comment = get_table_comment(alt_table_name, schema, engine)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/wrds2pg/wrds2pg.py", line 464, in get_table_comment
        if engine.dialect.has_table(engine.connect(), table_name, schema=schema):
                                    ^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
        return self._connection_cls(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
        Connection._handle_dbapi_exception_noconnection(
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
        raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
        self._dbapi_connection = engine.raw_connection()
                                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
        return self.pool.connect()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
        return _ConnectionFairy._checkout(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
        rec = pool._do_get()
              ^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
        with util.safe_reraise():
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
        return self._create_connection()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
        return _ConnectionRecord(self)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
        self.__connect()
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
        with util.safe_reraise():
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
        raise exc_value.with_traceback(exc_tb)
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
        self.dbapi_connection = connection = pool._invoke_creator(self)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
        return dialect.connect(*cargs, **cparams)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 616, in connect
        return self.loaded_dbapi.connect(*cargs, **cparams)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/martien/gow/venv_mint_gow/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied
    (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by iangow** [comment]
Good to hear. Only `WRDS_ID` should be relevant to that command. `DATA_DIR` could be useful.

I think the way I have written the reading of environment variables may mean that some of them are only read on first import. This package was code originally written in Perl. Only recently did I start to clean it up.

Merry Christmas? (I'm in the US … still 24 December here.)

**Comment by iangow** [comment]
`fe_sendauth: no password supplied` ... this relates to how your PostgreSQL database has been set up. You could set `PGPASSWORD` to whatever password you set up for that. Given that your `PGUSER` is `postgres`, this maybe some kind of default for the Ubuntu installation. If you don't know this, the worst case may require some `sudo`/`su` stuff to login to that and change it.

**Comment by iangow** [comment]
Once you've set up your password, Google `.pgpass` to learn how to set up your password so you don't see that error.

**Comment by blucap** [comment]
Yeap, it all works like a charm now!

For some reason unknown to me the password was not a problem until it was. pgpass came to the rescue
